AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Image Auto-Resizing Solution using AWS Lambda - 폴더별 특정 크기 리사이징'

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket for images
    Default: 'ckokservice'
  
  DestinationPrefix:
    Type: String
    Description: Prefix for resized images
    Default: 'resized'

Resources:
  # Lambda 실행 역할
  ImageResizeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${BucketName}/*'

  # 이미지 리사이징 Lambda 함수
  ImageResizeLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: folder-based-image-resize-function
      Handler: index.handler
      Role: !GetAtt ImageResizeLambdaRole.Arn
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 1024
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref BucketName
          DESTINATION_PREFIX: !Ref DestinationPrefix
      Code:
        S3Bucket: !Ref BucketName
        S3Key: lambda/image-resize-function.zip

  # Lambda 함수에 대한 S3 트리거 권한
  ImageResizeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ImageResizeLambdaFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${BucketName}'

  # S3 버킷 알림 설정
  S3BucketNotificationConfiguration:
    Type: AWS::S3::BucketNotification
    Properties:
      Bucket: !Ref BucketName
      LambdaConfigurations:
        - Event: 's3:ObjectCreated:*'
          Filter:
            S3Key:
              Rules:
                - Name: prefix
                  Value: profile-images/
                - Name: suffix
                  Value: .jpg
        - Event: 's3:ObjectCreated:*'
          Filter:
            S3Key:
              Rules:
                - Name: prefix
                  Value: profile-images/
                - Name: suffix
                  Value: .jpeg
        - Event: 's3:ObjectCreated:*'
          Filter:
            S3Key:
              Rules:
                - Name: prefix
                  Value: profile-images/
                - Name: suffix
                  Value: .png
        - Event: 's3:ObjectCreated:*'
          Filter:
            S3Key:
              Rules:
                - Name: prefix
                  Value: campaign-images/
                - Name: suffix
                  Value: .jpg
        - Event: 's3:ObjectCreated:*'
          Filter:
            S3Key:
              Rules:
                - Name: prefix
                  Value: campaign-images/
                - Name: suffix
                  Value: .jpeg
        - Event: 's3:ObjectCreated:*'
          Filter:
            S3Key:
              Rules:
                - Name: prefix
                  Value: campaign-images/
                - Name: suffix
                  Value: .png

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref ImageResizeLambdaFunction
  
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt ImageResizeLambdaFunction.Arn
  
  IAMRoleArn:
    Description: ARN of the IAM role used by Lambda
    Value: !GetAtt ImageResizeLambdaRole.Arn